version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the docs/sphinx directory with Sphinx
sphinx:
  configuration: docs/sphinx/conf.py
  fail_on_warning: true

# Dependencies required to build your docs
python:
  install:
    - method: pip
      path: .
    - requirements: docs/sphinx/requirements.txt
