name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install -g conventional-changelog conventional-changelog-angular

      - name: Generate changelog
        # run: conventional-changelog -p angular -i CHANGELOG.md -s -r 0
        run: conventional-changelog -p angular -i CHANGELOG.md -s

      # - name: Commit changelog
      #   run: |
      #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add CHANGELOG.md
      #     git commit -m "docs: update changelog for ${{ github.ref_name }}" || exit 0
      #     git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          # generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
